call plug#begin('~/.vim/plugged')
	Plug 'vimsence/vimsence'
	Plug 'sheerun/vim-polyglot'
	Plug 'Yggdroot/indentLine'
	Plug 'psliwka/vim-smoothie'
	Plug 'tpope/vim-commentary'
	Plug 'preservim/nerdtree'
call plug#end()

source $VIMRUNTIME/vimrc_example.vim
set hls
set is
set cb=unnamed
set gfn=Fixedsys:h10
set ts=2
set sw=2
set si
set nocompatible            " use new features whenever they are available
set nomodeline

syntax on
filetype on
filetype plugin on
filetype plugin indent on

set autoindent
set expandtab

" Automatically update changed files (but need to focus on the file)
set autoread
set hidden " needed for languageclient

" Misc {{{
set autoread                " auto re-read changes outside vim
set autowrite               " auto save before make/execute
set showcmd
set timeout                 " adjust timeout for mapped commands
set timeoutlen=1200

set smoothscroll
set background=dark
colorscheme iceberg
highlight Normal cterm=NONE ctermbg=NONE ctermfg=NONE gui=NONE guibg=NONE guifg=NONE
highlight LineNr NONE
set softtabstop=2
set tabstop=2
set shiftwidth=2
set expandtab
set bs=2                    " backspace should work as we expect
set history=50              " remember last 50 commands
set ruler                   " show cursor position in bottom line
set hlsearch                " highlight search result
" y and d put stuff into system clipboard (so that other apps can see it)
" set clipboard=unnamed,unnamedplus
set textwidth=0
" Open new split to right / bottom
set splitbelow
set splitright
set foldlevel=20

" Searching {{{
set incsearch               " show first match when start typing
set ignorecase              " default should ignore case
set smartcase               " use case sensitive if I use uppercase
" }}}

let mapleader = " "

" Keybinding
map <leader>y :w !xclip -selection clipboard<CR><ESC>
map <leader>Y :'<,'>w !xclip -selection clipboard<CR><ESC>
map <leader>t :t.<CR><ESC>
map <TAB> gt
map <leader><leader> :noh<CR>
autocmd filetype cpp nnoremap <C-9> :w <bar> !g++ -std=c++17 % -o %:r<CR>
autocmd filetype cpp nnoremap <C-0> :!./%:r<CR>

highlight clear CursorLineNR
set encoding=utf-8
set numberwidth=1
set wildmode=longest,list,full
set wildmenu
set nocursorline

